# Generated by Django 6.0.3 on 2026-03-18 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_credittransfer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credittransaction',
            options={'verbose_name': 'Historial de transacción', 'verbose_name_plural': 'Historial de transacciones'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Gestión de perfil', 'verbose_name_plural': 'Gestión de perfiles'},
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Carga'), ('transfer', 'Transferencia'), ('redeem', 'Consumo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.empresa'),
        ),
    ]
