# Generated by Django 6.0.3 on 2026-03-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_credittransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tipo',
            field=models.CharField(blank=True, choices=[('ADMIN_EMPRESA', 'Admin Empresa'), ('EMPLEADO', 'Empleado')], max_length=20, null=True),
        ),
    ]
