# Generated by Django 6.0.3 on 2026-03-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Carga'), ('transfer', 'Transferencia'), ('redeem', 'Consumo'), ('refund', 'Devolución')], max_length=20),
        ),
    ]
