# Generated by Django 6.0.3 on 2026-03-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='motivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
