# Generated by Django 6.0.3 on 2026-03-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_credittransaction_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='reverted',
            field=models.BooleanField(default=False),
        ),
    ]
