# Generated by Django 6.0.3 on 2026-04-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_credittransaction_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='codigo_sap',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
