# Generated by Django 6.0.3 on 2026-04-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_empresa_codigo_sap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='balance',
            new_name='balance_empresa',
        ),
        migrations.AddField(
            model_name='wallet',
            name='balance_personal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
