# Generated by Django 6.0.3 on 2026-04-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_balance_wallet_balance_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
