# Generated by Django 6.0.3 on 2026-04-05 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_userprofile_nacionalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divisiones', to='accounts.empresa'),
        ),
    ]
