# Generated by Django 6.0.3 on 2026-04-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_empresa_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase_empresa', 'Compra empresarial'), ('purchase_personal', 'Compra particular'), ('transfer', 'Transferencia'), ('redeem', 'Consumo'), ('refund_empresa', 'Devolución automática'), ('adjustment', 'Ajuste Manual')], max_length=20),
        ),
    ]
